gui:
  authorColors:
    'Pierluigi Di Cerbo': 'blue'
git:
  autoStageResolvedConflicts: false
  mainBranches:
    - master
  autoFetch: false
  autoRefresh: false
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --pretty=medium {{branchName}} --oneline
  log:
    showWholeGraph: true
  autoForwardBranches: none
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side
