#!/bin/bash

xrandr --newmode "3840x2160_60.00"  712.75  3840 4160 4576 5312  2160 2163 2168 2237 -hsync +vsync

xrandr --addmode Virtual-1 3840x2160_60.00

xrandr --output Virtual-1 --mode 3840x2160_60.00

sed -i "s/font = 'DejaVu Sans Mono:pixelsize=9'/font = 'DejaVu Sans Mono:pixelsize=14'/" "$HOME/.config/conky_cfg/aw_conky"
$HOME/.scripts/restart_conky

# sed -i "s/Font:size=6/Font:size=9/" "$HOME/.Xresources"
# xrdb -merge $HOME/.Xresources

sed -i "s/Envy Code R 8/Envy Code R 11/" "$HOME/.config/awesome/themes/zenburn/theme.lua"
sed -i "s/theme.menu_height = 15/theme.menu_height = 20/" "$HOME/.config/awesome/themes/zenburn/theme.lua"
sed -i "s/theme.menu_width  = 140/theme.menu_width  = 150/" "$HOME/.config/awesome/themes/zenburn/theme.lua"
sed -i "s/awful.wibar({ position = \"top\", screen = s, height = 18, bg = theme.bg_normal, fg = theme.fg_normal })/awful.wibar({ position = \"top\", screen = s, height = 28, bg = theme.bg_normal, fg = theme.fg_normal })/" "$HOME/.config/awesome/themes/zenburn/theme.lua"

awesome-client 'awesome.restart()'
