#!/bin/bash

mkdir -p $HOME/Downloads
cd $HOME/Downloads

# download latest available version
wget https://aur.archlinux.org/cgit/aur.git/snapshot/tdrop.tar.gz

# unpack downloaded package
tar -xzf tdrop.tar.gz

if [ ! -d tdrop ]
then
    echo -e "something wrong happens during package decompression\nexit.."
    exit 42
fi

cd tdrop

# build package
makepkg -s --noconfirm

if [ ! -f tdrop-*.pkg.tar.zst ]
then
    echo -e "something wrong happens during package construction\nexit.."
    exit 42
fi

# install package
sudo pacman --noconfirm -U tdrop-*.pkg.tar.zst || {
    echo -e "invalid or corrupted package (or wrong password inserted for three times...)\nexit"
    exit 42
}

cd ..

# cleaning...
echo -e "\n removing compressed package and build folder"
rm -rf tdrop*
